[package]
name = "baseview"
version = "0.1.0"
authors = ["William Light <git@wrl.lhiaudio.com>", "Mirko Covizzi <mrkcvzz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["libloaderapi", "winuser", "windef", "minwindef", "guiddef", "combaseapi"] }
